//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySoTietKiem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTBCMODONGSOTHANG
    {
        public int MaCTBaoCaoMoDongSo { get; set; }
        public Nullable<int> MaBaoCaoMoDongSo { get; set; }
        public Nullable<int> Ngay { get; set; }
        public Nullable<int> SoMo { get; set; }
        public Nullable<int> SoDong { get; set; }
        public Nullable<int> ChenhLech { get; set; }
    
        public virtual BCMODONGSOTHANG BCMODONGSOTHANG { get; set; }
    }
}
