//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySoTietKiem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAITIETKIEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOAITIETKIEM()
        {
            this.BCDOANHSOTHEONGAYs = new HashSet<BCDOANHSOTHEONGAY>();
            this.BCMODONGSOTHANGs = new HashSet<BCMODONGSOTHANG>();
            this.SOTIETKIEMs = new HashSet<SOTIETKIEM>();
        }
    
        public int MaLoaiTietKiem { get; set; }
        public string TenLoaiTietKiem { get; set; }
        public Nullable<bool> BiXoa { get; set; }
        public Nullable<decimal> LaiSuat { get; set; }
        public Nullable<int> ThoiGianGoiToiThieu { get; set; }
        public Nullable<bool> PhaiRutToanBo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BCDOANHSOTHEONGAY> BCDOANHSOTHEONGAYs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BCMODONGSOTHANG> BCMODONGSOTHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOTIETKIEM> SOTIETKIEMs { get; set; }
    }
}
