//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySoTietKiem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUGOITIEN
    {
        public int MaPhieuGoiTien { get; set; }
        public int MaSo { get; set; }
        public Nullable<System.DateTime> NgayGoi { get; set; }
        public Nullable<int> SoTienGoi { get; set; }
    
        public virtual SOTIETKIEM SOTIETKIEM { get; set; }
    }
}
