//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySoTietKiem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class THAMSO
    {
        public Nullable<int> SoTienGoiBanDauToiThieu { get; set; }
        public Nullable<int> SoTienGoiThemToiThieu { get; set; }
        public Nullable<bool> TuDongSoKhiRutHetTien { get; set; }
        public string Id { get; set; }
    }
}
